#os: Visual Studio 2015

environment:
  secret_var:
    secure: /LqjEnMSfmWPx+VR6AhR4A==

before_build:
  - cmd: echo before build

#build_script:
#- where msbuild.exe
#- echo %secret_var%

test: off
deploy: off

# build 5

notifications:
- provider: Slack
  incoming_webhook:
    secure: dyGwpNHyWptB4qqclSSWT83Bozb39uiA2uqElZv2P2uA2jjLxeg5So/ZRDr968GYbaH+y42KVCNtNUNsIGG+HlEtu5kGb/u4QmKWbzOQImE=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
