version: "{build}"

init:
    echo test!

environment:
  variable1: also defined in YAML
  VARIABLE3: defined in YAML
  
#build_script:
#  - ps: .\build.cmd
#  
test:
  assemblies:
    - SimpleConsole.Tests.dll

branches:
  except:
    - gh-pages
    - release
