#os: test

install:
  - perl --version
  - ps: Install-Product node 1
  - node --version
  - ps: Start-sleep -s 5
  - ps: Install-Product node 0.10
  - node --version

build: off
test: off
deploy: off
