SimpleConsole\bin\debug\SimpleConsole.exe -1073741819
set LASTERROR=%ERRORLEVEL%
IF %LASTERROR% NEQ 0 (
  IF %LASTERROR% NEQ -1073741819 EXIT /B %LASTERROR%
)

SimpleConsole\bin\debug\SimpleConsole.exe 3
set LASTERROR=%ERRORLEVEL%
IF %LASTERROR% NEQ 0 (
  IF %LASTERROR% NEQ -1073741819 EXIT /B %LASTERROR%
)

SimpleConsole\bin\debug\SimpleConsole.exe 1
set LASTERROR=%ERRORLEVEL%
IF %LASTERROR% NEQ 0 (
  IF %LASTERROR% NEQ -1073741819 EXIT /B %LASTERROR%
)

rem SimpleConsole\bin\debug\SimpleConsole.exe -2 || IF %ERRORLEVEL% NEQ -1073741819 EXIT /B %ERRORLEVEL%
